# Change these first
owner: gcloudlab # Your GitHub organization or username, where this repository lives
repo: online-monitoring # The name of this repository

sites:
  - name: GCloud 云盘
    url: https://gcloud.website

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /online-monitoring
  logoUrl: https://img-yesmore.vercel.app//gcloud/gcloudx.png
  name: GCloud
  introTitle: "**GCloud云盘** 性能监控平台."
  introMessage: GCloud 云盘 ([here](https://gcloud.website/)) 是一款在线云盘服务网站，提供文件资源存储、转存等便捷功能。<hr> ![Hits](https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgcloud.website%2Fhit-counter&count_bg=%2379C83D&title_bg=%23555555&icon=awesomelists.svg&icon_color=%230AFFAB&title=visitor&edge_flat=true) ![](https://img.shields.io/github/stars/yesmore/gcloud-app.svg?logo=github&style=flat-square)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Online 
      href: https://gcloud.website

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
